package com.zija.ai.internal;

final class ErrorCodes {

    static final String CONFIGURATION_VERSION_CONFLICT = "AI_CONFIGURATION_VERSION_CONFLICT";
    static final String INVALID_CONFIGURATION = "AI_INVALID_CONFIGURATION";
    static final String KNOWLEDGE_SOURCE_NOT_FOUND = "AI_KNOWLEDGE_SOURCE_NOT_FOUND";
    static final String KNOWLEDGE_SOURCE_FORMAT_UNSUPPORTED = "AI_KNOWLEDGE_SOURCE_FORMAT_UNSUPPORTED";
    static final String KNOWLEDGE_SOURCE_STATE_CONFLICT = "AI_KNOWLEDGE_SOURCE_STATE_CONFLICT";
    static final String REQUEST_LIMITED = "AI_REQUEST_LIMITED";

    private ErrorCodes() {
    }
}
