import { describe, expect, it } from "vitest"
import { ACTION_LABELS } from "./audit"

// 后端 com.zija.system.SystemApi.AuditAction 的完整 action 集（新增后端 action 时同步更新此列表）
const BACKEND_ACTIONS = [
  "LOGIN_SUCCESS",
  "LOGIN_FAILURE",
  "LOGOUT",
  "PASSWORD_CHANGED",
  "DISPLAY_NAME_CHANGED",
  "HOUSEHOLD_INITIALIZED",
  "MEMBER_JOINED",
  "MEMBER_DEACTIVATED",
  "MEMBER_REACTIVATED",
  "ROLE_CHANGED",
  "OWNERSHIP_TRANSFERRED",
  "INVITATION_CREATED",
  "INVITATION_REDEEMED",
  "OWNER_RECOVERY",
  "CATEGORY_CREATED",
  "CATEGORY_UPDATED",
  "CATEGORY_ARCHIVED",
  "CATEGORY_RESTORED",
  "CATEGORY_MOVED",
  "BRAND_CREATED",
  "BRAND_UPDATED",
  "BRAND_ARCHIVED",
  "BRAND_RESTORED",
  "UNIT_CREATED",
  "UNIT_UPDATED",
  "UNIT_ARCHIVED",
  "UNIT_RESTORED",
  "UNIT_DECIMAL_SCALE_UPDATED",
  "TAG_CREATED",
  "TAG_UPDATED",
  "TAG_ARCHIVED",
  "TAG_RESTORED",
  "ITEM_CREATED",
  "ITEM_UPDATED",
  "ITEM_ARCHIVED",
  "ITEM_RESTORED",
  "ITEM_COVER_UPLOADED",
  "ITEM_COVER_REMOVED",
  "FILE_UPLOADED",
  "FILE_RENAMED",
  "FILE_MOVED",
  "FILE_DELETED",
  "FILE_RESTORED",
  "FILE_PURGED",
  "LOCATION_CREATED",
  "LOCATION_RENAMED",
  "LOCATION_MOVED",
  "LOCATION_DELETED",
  "INVENTORY_INBOUND",
  "INVENTORY_CONSUME",
  "INVENTORY_LOSS",
  "INVENTORY_TRANSFER",
  "INVENTORY_REVERSAL",
  "INVENTORY_STOCKTAKE_CONFIRM",
  "INVENTORY_STOCKTAKE_CANCEL",
  "REMINDER_RULE_UPDATE",
  "REMINDER_TASK_SNOOZED",
  "REMINDER_TASK_COMPLETED",
  "REMINDER_TASK_IGNORED",
  "REMINDER_TASK_REOPENED",
  "MAIL_SETTING_UPDATE",
  "MAIL_DIGEST_SENT",
  "MAIL_SEND_FAILED",
  "REMINDER_EVENT_POISON",
  "EXPORT_PERFORMED",
  "REPORTING_PROJECTION_REBUILT",
  "REPORTING_EVENT_ABANDONED",
]

describe("ACTION_LABELS", () => {
  it("covers every backend audit action with a non-empty Chinese label", () => {
    for (const action of BACKEND_ACTIONS) {
      const label = ACTION_LABELS[action]
      expect(label, `ACTION_LABELS missing label for ${action}`).toBeTruthy()
      expect(label!.trim(), `label for ${action} is empty`).not.toBe("")
    }
  })
})
