// ==================== Error Codes ====================
// 后端错误码常量镜像（RFC 7807 problem.errorCode 取值）。
// 来源：各模块 internal/ErrorCodes.java 与 com.zija.shared.ZijaErrorCodes。
// 前端一律从这里导入，禁止在组件/测试中硬编码错误码字面量；
// 后端新增错误码时请同步维护本文件。

// ==================== Shared (ZijaErrorCodes) ====================

/** 请求字段校验失败（根包校验处理器与 inventory 共用）。 */
export const VALIDATION_FAILED = "VALIDATION_FAILED";

/** 事件处理异常信息缺失时的兜底错误名（reminder 与 reporting 共用）。 */
export const UNKNOWN_ERROR = "UnknownError";

// ==================== Identity ====================

export const AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED";
export const AUTH_LOGIN_RATE_LIMITED = "AUTH_LOGIN_RATE_LIMITED";
export const IDENTITY_USERNAME_TAKEN = "IDENTITY_USERNAME_TAKEN";
export const IDENTITY_VERSION_CONFLICT = "IDENTITY_VERSION_CONFLICT";

// ==================== Household ====================

export const HOUSEHOLD_ALREADY_INITIALIZED = "HOUSEHOLD_ALREADY_INITIALIZED";
export const HOUSEHOLD_INSUFFICIENT_ROLE = "HOUSEHOLD_INSUFFICIENT_ROLE";
export const HOUSEHOLD_MEMBER_CONCURRENT_UPDATE = "HOUSEHOLD_MEMBER_CONCURRENT_UPDATE";
export const HOUSEHOLD_MEMBER_NOT_ACTIVE = "HOUSEHOLD_MEMBER_NOT_ACTIVE";
export const HOUSEHOLD_REQUEST_INVALID = "HOUSEHOLD_REQUEST_INVALID";
export const HOUSEHOLD_STATE_CONFLICT = "HOUSEHOLD_STATE_CONFLICT";
export const HOUSEHOLD_TOKEN_INVALID = "HOUSEHOLD_TOKEN_INVALID";

// ==================== Catalog ====================

export const CATALOG_ARCHIVED_DICTIONARY = "CATALOG_ARCHIVED_DICTIONARY";
export const CATALOG_CATEGORY_HAS_CHILDREN = "CATALOG_CATEGORY_HAS_CHILDREN";
export const CATALOG_CYCLE_DETECTED = "CATALOG_CYCLE_DETECTED";
export const CATALOG_DICTIONARY_NAME_EXISTS = "CATALOG_DICTIONARY_NAME_EXISTS";
export const CATALOG_UNIT_PRECISION_INVALID = "CATALOG_UNIT_PRECISION_INVALID";
export const CATALOG_UNIT_PRECISION_LOCKED = "CATALOG_UNIT_PRECISION_LOCKED";
export const CATALOG_VERSION_CONFLICT = "CATALOG_VERSION_CONFLICT";
export const CATALOG_COVER_NOT_ELIGIBLE = "CATALOG_COVER_NOT_ELIGIBLE";

// ==================== Location ====================

export const LOCATION_CYCLE = "LOCATION_CYCLE";
export const LOCATION_HAS_CHILDREN = "LOCATION_HAS_CHILDREN";
export const LOCATION_REFERENCED = "LOCATION_REFERENCED";
export const LOCATION_VERSION_CONFLICT = "LOCATION_VERSION_CONFLICT";

// ==================== File ====================

export const FILE_MEDIA_TYPE_UNSUPPORTED = "FILE_MEDIA_TYPE_UNSUPPORTED";
export const FILE_SIGNATURE_MISMATCH = "FILE_SIGNATURE_MISMATCH";
export const FILE_TOO_LARGE = "FILE_TOO_LARGE";
export const FILE_NAME_DUPLICATE = "FILE_NAME_DUPLICATE";
export const FILE_NOT_AVAILABLE = "FILE_NOT_AVAILABLE";
export const FILE_NOT_IN_RECYCLE_BIN = "FILE_NOT_IN_RECYCLE_BIN";

// ==================== Inventory ====================

export const INVENTORY_ARCHIVED_ITEM = "INVENTORY_ARCHIVED_ITEM";
export const INVENTORY_IDEMPOTENCY_CONFLICT = "INVENTORY_IDEMPOTENCY_CONFLICT";
export const INVENTORY_INSUFFICIENT_STOCK = "INVENTORY_INSUFFICIENT_STOCK";
export const INVENTORY_LOT_NOT_FOUND = "INVENTORY_LOT_NOT_FOUND";
export const INVENTORY_LOT_VERSION_CONFLICT = "INVENTORY_LOT_VERSION_CONFLICT";
export const INVENTORY_MOVEMENT_ALREADY_REVERSED = "INVENTORY_MOVEMENT_ALREADY_REVERSED";
export const INVENTORY_QUANTITY_PRECISION_INVALID = "INVENTORY_QUANTITY_PRECISION_INVALID";
export const INVENTORY_REVERSAL_NOT_ALLOWED = "INVENTORY_REVERSAL_NOT_ALLOWED";
export const INVENTORY_REVERSAL_WOULD_NEGATIVE = "INVENTORY_REVERSAL_WOULD_NEGATIVE";
export const INVENTORY_STOCKTAKE_NOT_DRAFT = "INVENTORY_STOCKTAKE_NOT_DRAFT";
export const INVENTORY_STOCKTAKE_STALE = "INVENTORY_STOCKTAKE_STALE";

// ==================== Reminder ====================

export const MAIL_SETTING_VERSION_CONFLICT = "MAIL_SETTING_VERSION_CONFLICT";
export const REMINDER_INVALID_ARGUMENT = "REMINDER_INVALID_ARGUMENT";
export const REMINDER_RULE_EXPIRY_DAYS_INVALID = "REMINDER_RULE_EXPIRY_DAYS_INVALID";
export const REMINDER_RULE_LOW_STOCK_INVALID = "REMINDER_RULE_LOW_STOCK_INVALID";
export const REMINDER_RULE_NOT_INITIALIZED = "REMINDER_RULE_NOT_INITIALIZED";
export const REMINDER_RULE_VERSION_CONFLICT = "REMINDER_RULE_VERSION_CONFLICT";
export const REMINDER_TASK_INVALID_TRANSITION = "REMINDER_TASK_INVALID_TRANSITION";
export const REMINDER_TASK_NOT_FOUND = "REMINDER_TASK_NOT_FOUND";
export const REMINDER_TASK_SNOOZE_UNTIL_INVALID = "REMINDER_TASK_SNOOZE_UNTIL_INVALID";

// ==================== AI ====================

export const AI_CONFIGURATION_VERSION_CONFLICT = "AI_CONFIGURATION_VERSION_CONFLICT";
export const AI_INVALID_CONFIGURATION = "AI_INVALID_CONFIGURATION";
export const AI_REQUEST_LIMITED = "AI_REQUEST_LIMITED";

// ==================== Reporting ====================

export const REPORTING_EXPORT_TOO_LARGE = "REPORTING_EXPORT_TOO_LARGE";
export const REPORTING_INVALID_REQUEST = "REPORTING_INVALID_REQUEST";
